### ISSUE TITLE
Чек лабы 3

### ISSUE THREAD

**Issue by H30H** [Kate-Tol3/LAB3.3#1]
- [x] Метод должен быть приватным
https://github.com/Kate-Tol3/LAB3.3/blob/724e8f8ef2dcf865fd01891c58877296f59fbe74/Basic_Structures/AVLTree.h#L183

- [x] Все включения внешних зависимостей должны быть сверху файла
https://github.com/Kate-Tol3/LAB3.3/blob/724e8f8ef2dcf865fd01891c58877296f59fbe74/GUI.cpp#L178-L183

- [x] Какие-то кривые пути
https://github.com/Kate-Tol3/LAB3.3/blob/724e8f8ef2dcf865fd01891c58877296f59fbe74/GUI.h#L9-L10

**Comment by Kate-Tol3** [comment]
Исправила
